export const COUNTRY_ADD_LOAD = "COUNTRY_ADD_LOAD";
export const COUNTRY_ADDED_SUCCESS = "COUNTRY_ADDED_SUCCESS";
export const COUNTRY_ADD_FAILURE = "COUNTRY_ADD_FAILURE";
export const CITY_ADD_LOAD = "CITY_ADD_LOAD";
export const CITY_ADDED_SUCCESS = "CITY_ADDED_SUCCESS";
export const CITY_ADD_FAILURE = "CITY_ADD_FAILURE";